/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp;

import controller.ProjectController;
import controller.TaskController;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;
import model.Project;
import model.Task;

public class App {

    public static void main(String[] args) throws SQLException {
//        ProjectController projectController = new ProjectController();
//
//        Project project = new Project();
//        project.setName("Projeto teste");
//        project.setDescription("description");
//        projectController.save(project);
//
//        project.setId(1);
//        project.setName("Novo nome do projeto");
//        project.setDescription("description");
//        
//        projectController.update(project);
        
//        List<Project> projects = projectController.getAll();
//        System.out.println("Total de projetos = " + projects.size());
//        
//
//        TaskController taskController = new TaskController();
//
//        Task task = new Task();
//        task.setIdProject(3);
//        task.setName("Outra nova tarefa do projeto 3");
//        task.setDescription("description");
//        task.setNotes("Uma observação aleatória");
//        task.setIsCompleted(false);
//        task.setDeadline(new Date());
        
//        taskController.save(task);
        
//        task.setName("Novo nome da tarefa");
//        
//        taskController.update(task);
        
//        List<Task> tasks = taskController.getAll(2);
//        System.out.println("Total de projetos = " + tasks);
//        
//        taskController.removeById(3);
//        
//        tasks = taskController.getAll(2);
//        System.out.println("\n\nTotal de projetos = " + tasks);
    }
}
